version: '3'

services:
  django:
    build: ./backend/production_line
    volumes:
      - ./backend/production_line:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://admin:admin123@postgres:5432/postgresdb
      - SECRET_KEY=dev-key-secure-enough-for-local-dev
    depends_on:
      - postgres
    command: python manage.py runserver 0.0.0.0:8000
  
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgresdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
