# Generated by Django 5.1.7 on 2025-04-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='start_location',
            field=models.CharField(default='Warsaw, Poland (Basecamp)', max_length=255),
        ),
    ]
